## @section Global
## @param  defaultNamespace To override the namespace use the `--namespace` flag. This default is provided to ensure that the kustomize build charts in `/templates` deploy correctly when no `namespace` is provided via the `-n` flag.

## @section Sidecar configuration
## @param   sidecarConfiguration.envVarPrefix Sets the prefix for all environment variables set in the injected sidecar.
## @param   sidecarConfiguration.port Sets the value of the `XXX_PORT` environment variable for the injected sidecar.
## @param   sidecarConfiguration.metricsPort Sets the value of the `XXX_METRICS_PORT` environment variable for the injected sidecar.
## @param   sidecarConfiguration.socketPath Sets the value of the `XXX_SOCKET_PATH` environment variable for the injected sidecar.

## @param   sidecarConfiguration.image.repository Sets the image for the injected sidecar.
## @param   sidecarConfiguration.image.tag Sets the version tag for the injected sidecar.

## @param   sidecarConfiguration.providerArgs Used to append arguments to the sidecar startup command. This value is a comma separated string of key values separated by '=', e.g. `key=value,key2=value2` results in the appending of `--sync-provider-args key=value --sync-provider-args key2=value2`.
## @param   sidecarConfiguration.defaultSyncProvider Sets the value of the `XXX_SYNC_PROVIDER` environment variable for the injected sidecar container. There are 3 valid sync providers: `kubernetes`, `filepath` and `http`.
## @param   sidecarConfiguration.logFormat Sets the value of the `XXX_LOG_FORMAT` environment variable for the injected sidecar container. There are 2 valid log formats: `json` and `console`.
## @param   sidecarConfiguration.evaluator Sets the value of the `XXX_EVALUATOR` environment variable for the injected sidecar container.
## @param   sidecarConfiguration.probesEnabled Enable or Disable Liveness and Readiness probes of the flagd sidecar. When enabled, HTTP probes( paths - `/readyz`, `/healthz`) are set with an initial delay of 5 seconds.
## @param   sidecarConfiguration.debugLogging Controls the addition of the `--debug` flag to the container startup arguments.

## @section Operator resource configuration

## @param   controllerManager.kubeRbacProxy.image.repository Sets the image for the kube-rbac-proxy.
## @param   controllerManager.kubeRbacProxy.image.tag Sets the version tag for the kube-rbac-proxy.

## @param   controllerManager.kubeRbacProxy.resources.limits.cpu Sets cpu resource limits for kube-rbac-proxy.
## @param   controllerManager.kubeRbacProxy.resources.limits.memory Sets memory resource limits for kube-rbac-proxy.

## @param   controllerManager.kubeRbacProxy.resources.requests.cpu Sets cpu resource requests for kube-rbac-proxy.
## @param   controllerManager.kubeRbacProxy.resources.requests.memory Sets memory resource requests for kube-rbac-proxy.

## @param   controllerManager.manager.image.repository Sets the image for the operator.
## @param   controllerManager.manager.image.tag Sets the version tag for the operator.

## @param   controllerManager.manager.resources.limits.cpu Sets cpu resource limits for operator.
## @param   controllerManager.manager.resources.limits.memory Sets memory resource limits for operator.

## @param   controllerManager.manager.resources.requests.cpu Sets cpu resource requests for operator.
## @param   controllerManager.manager.resources.requests.memory Sets memory resource requests for operator.

## @param   controllerManager.replicas Sets number of replicas of the OpenFeature operator pod.

## @param   managerConfig.controllerManagerConfigYaml.health.healthProbeBindAddress Sets the bind address for health probes.
## @param   managerConfig.controllerManagerConfigYaml.metrics.bindAddress Sets the bind address for metrics.
## @param   managerConfig.controllerManagerConfigYaml.webhook.port Sets the bind address for webhook.

## @section Flagd-proxy configuration

## @param   flagdProxyConfiguration.port Sets the port to expose the sync API on.
## @param   flagdProxyConfiguration.metricsPort Sets the port to expose the metrics API on.

## @param   flagdProxyConfiguration.image.repository Sets the image for the flagd-proxy deployment.
## @param   flagdProxyConfiguration.image.tag Sets the tag for the flagd-proxy deployment.

## @param   flagdProxyConfiguration.debugLogging Controls the addition of the `--debug` flag to the container startup arguments.
