# permissions for end users to view featureflagconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: featureflagconfiguration-viewer-role
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - featureflagconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.openfeature.dev
  resources:
  - featureflagconfigurations/status
  verbs:
  - get
