# permissions for end users to edit sidecarconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecarconfiguration-editor-role
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - sidecarconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openfeature.dev
  resources:
  - sidecarconfigurations/status
  verbs:
  - get
