# permissions for end users to edit featureflagsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: featureflagsource-editor-role
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - featureflagsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openfeature.dev
  resources:
  - featureflagsources/status
  verbs:
  - get
