apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: featureflag-sample
spec:
  flagSpec:
    flags:
      "simple-flag":
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "on"
