apiVersion: core.openfeature.dev/v1beta2
kind: FeatureFlagSource
metadata:
  labels:
    app.kubernetes.io/name: featureflagsource
    app.kubernetes.io/instance: featureflagsource-sample
    app.kubernetes.io/part-of: open-feature-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: open-feature-operator
  name: featureflagsource-sample
spec:
  # TODO(user): Add fields here
